### ISSUE TITLE
Something different with a random call?

### ISSUE THREAD

**Issue by jcfrosty** [D00Med/LegendofMinetest#37] opened 2018-06-28 19:59 UTC
2018-06-28 15:35:46: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'mobs_loz' in callback luaentity_Punch(): ...games/LegendofMinetest-master/mods/mobs_redo/api.lua:338: bad argument #2 to 'random' (interval is empty)
2018-06-28 15:35:46: ERROR[Main]: stack traceback:
2018-06-28 15:35:46: ERROR[Main]:   [C]: in function 'random'
2018-06-28 15:35:46: ERROR[Main]:   ...games/LegendofMinetest-master/mods/mobs_redo/api.lua:338: in function 'item_drop'
2018-06-28 15:35:46: ERROR[Main]:   ...games/LegendofMinetest-master/mods/mobs_redo/api.lua:406: in function 'check_for_death'
2018-06-28 15:35:46: ERROR[Main]:   ...games/LegendofMinetest-master/mods/mobs_redo/api.lua:2067: in function <...games/LegendofMinetest-master/mods/mobs_redo/api.lua:1949>
2018-06-28 15:35:46: ERROR[Main]:   [C]: in function 'punch'

**Comment by D00Med** [comment] 2018-06-28 21:26
Ooh this is a tricky one, I'll try updating mobs_redo and seeing what happens

**Comment by jcfrosty** [comment] 2018-07-05 20:41
forgive me if I seem impatient, I really do appreciate the work, but I am curious what the issue is. I'm starting to feel I need to learn lua more lol. My programming skills are very introductory..

**Comment by D00Med** [comment] 2018-07-05 21:27
I don't know what the issue is :/
That's why I'm just going to try updating mobs_redo. 
But I just had an idea, maybe you're right and it is from a random number.
It could be because of something to do with the drop chance of items.
What were you doing when you got this error?

**Comment by D00Med** [comment] 2018-07-05 21:28
And about your programming skills, mine aren't exactly great either 😅

**Comment by jcfrosty** [comment] 2018-07-05 21:51
It happens when I attempted to launch the game.

**Comment by D00Med** [comment] 2018-07-05 21:57
Oh :/

**Comment by jcfrosty** [comment] 2018-07-07 06:05
OK, I've tested Regnum-3.2.9 . Not sure I understand the point of that game, but OK. It only had one issue with the music loading mod, after i removed that one plugin, Game ran smooth, no other issues.

I figured it could be my version of lua so I upgraded to 5.3.3 from 5.1, no change.
So I tried recompiling and installing minetest 4.7.1, no change.

All the errors I get are the same errors no matter what I do.

**Comment by D00Med** [comment] 2018-07-07 06:26
Oh :/ that's a shame.

**Comment by D00Med** [comment] 2018-07-07 06:33
![thing](https://user-images.githubusercontent.com/19916704/42407629-5388da70-8203-11e8-8d58-33caac22f84b.PNG)
I'm thinking the error has something to do with this. 
It's pretty frustrating, if other people are getting these errors it's going to seriously mess with situations where the min/max numbers are variable

**Comment by D00Med** [comment] 2018-07-07 06:43
I fixed the error in the update branch, but the update branch also now has the incomplete villages I'm working on. Just so you know.

**Comment by jcfrosty** [comment] 2018-07-07 14:48
Greatly appreciated! My son is driving me nuts to play this game so I'm
trying to setup a local server for just him and me.

**Comment by mckaygerhard** [comment] 2022-02-02 13:55
this was fixed since PR #39 was merged with commit 5e4e39e  commit 5e4e39e and    commit acf7cd2

**Closed as completed by mckaygerhard** 2022-02-02 13:55 UTC
Labels: bug
